version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: sheepfish
      POSTGRES_PASSWORD: postgres
    ports:
      - "5416:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: cache
    ports:
      - "6379:6379"

  wkhtmltopdf:
    image: openlabs/docker-wkhtmltopdf-aas
    container_name: wkhtmltopdf
    ports:
      - "5001:80"


volumes:
  postgres_data:



