# Generated by Django 4.2.5 on 2023-09-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='type',
            field=models.CharField(choices=[('client', 'client'), ('kitchen', 'kitchen')]),
        ),
    ]
